name: CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build and run
      run: |
        ./gradlew build
        java -jar WebCamTimeLapse-cli.jar | grep Usage
    - uses: actions/upload-artifact@v4
      with:
       name: WebCamTimeLapse-CLI
       path: WebCamTimeLapse-cli.jar
    - uses: actions/upload-artifact@v4
      with:
       name: WebCamTimeLapse-GUI
       path: WebCamTimeLapse-gui.jar
